refactor(RHTAPREL-643): change advisory task error handling
This commit changes the script in the create-advisory-task to trap all
exits instead of just error to improve the output returned to the
internal request. Prior to this change, if the git clone failed, it
would return an error about the checkout of the revision failing as it
would not exit early enough.

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

diff --git a/internal-services/catalog/create-advisory-task.yaml b/internal-services/catalog/create-advisory-task.yaml
--- a/internal-services/catalog/create-advisory-task.yaml
+++ b/internal-services/catalog/create-advisory-task.yaml
@@ -58,19 +58,21 @@ spec:
               key: git_author_email
       script: |
           #!/usr/bin/env sh
-          set -ox pipefail
+          set -eo pipefail
 
-          # This should get overwritten if any command fails
-          echo -n "Success" > $(results.result.path)
-
-          failfunc() {
+          exitfunc() {
               local err=$1
               local line=$2
               local command="$3"
-              echo -n "$0: ERROR '$command' failed at line $line - exited with status $err" > $(results.result.path)
-              exit 0 # exit the script cleanly as there is no point in proceeding past an error
+              if [ $err -eq 0 ] ; then
+                  echo -n "Success" > $(results.result.path)
+              else
+                  echo -n "$0: ERROR '$command' failed at line $line - exited with status $err" > $(results.result.path)
+              fi
+              exit 0 # exit the script cleanly as there is no point in proceeding past an error or exit call
           }
-          trap 'failfunc $? $LINENO "$BASH_COMMAND"' ERR # the task should never fail with nonzero exit code
+          # due to set -e, this catches all EXIT and ERR calls and the task should never fail with nonzero exit code
+          trap 'exitfunc $? $LINENO "$BASH_COMMAND"' EXIT
 
           REPO_BRANCH=main
           REPO=$(jq -r '.repo' <<< '$(params.advisory_json)')
