fix(RELEASE-1108): improve error messaging
- capture the error message when validating.

Signed-off-by: Scott Hebert <scoheb@gmail.com>

diff --git a/internal-services/catalog/pulp-push-disk-images-task.yaml b/internal-services/catalog/pulp-push-disk-images-task.yaml
--- a/internal-services/catalog/pulp-push-disk-images-task.yaml
+++ b/internal-services/catalog/pulp-push-disk-images-task.yaml
@@ -197,18 +197,30 @@ spec:
         process_component_for_developer_portal() { # Expected argument are [component json], [content_directory]
           COMPONENT=$1
 
-          productName=$(jq -er '.contentGateway.productName' <<< "${COMPONENT}") \
-            || (echo Missing contentGateway.productName value for component. This should be an existing product in the \
-                Developer Portal. Failing && exit 1)
-          productCode=$(jq -er '.contentGateway.productCode' <<< "${COMPONENT}") \
-            || (echo Missing contentGateway.productCode value for component. This should be an existing product in the \
-                Developer Portal. Failing && exit 1)
-          productVersionName=$(jq -er '.contentGateway.productVersionName' <<< "${COMPONENT}") \
-            || (echo Missing contentGateway.productVersionName value for component. This should be an existing product \
-                in the Developer Portal. Failing && exit 1)
-          filePrefix=$(jq -er '.contentGateway.filePrefix' <<< "${COMPONENT}") \
-            || (echo Missing contentGateway.filePrefix value for component. This should be the prefix for files to \
-                upload to the Developer Portal. Failing && exit 1)
+          productName=$(jq -r '.contentGateway.productName // ""' <<< "${COMPONENT}")
+          if [ "${productName}" == "" ]; then
+            echo "Missing contentGateway.productName value for component. This should be an existing product in the \
+                  Developer Portal. Failing" | tee -a "$STDERR_FILE"
+            exit 1
+          fi
+          productCode=$(jq -r '.contentGateway.productCode // ""' <<< "${COMPONENT}")
+          if [ "${productCode}" == "" ]; then
+            echo "Missing contentGateway.productCode value for component. This should be an existing product in the \
+                  Developer Portal. Failing" | tee -a "$STDERR_FILE"
+            exit 1
+          fi
+          productVersionName=$(jq -r '.contentGateway.productVersionName // ""' <<< "${COMPONENT}")
+          if [ "${productVersionName}" == "" ]; then
+            echo "Missing contentGateway.productVersionName value for component. This should be an existing product \
+                  in the Developer Portal. Failing" | tee -a "$STDERR_FILE"
+            exit 1
+          fi
+          filePrefix=$(jq -r '.contentGateway.filePrefix // ""' <<< "${COMPONENT}")
+          if [ "${filePrefix}" == "" ]; then
+            echo "Missing contentGateway.filePrefix value for component. This should be the prefix for files to \
+                  upload to the Developer Portal. Failing" | tee -a "$STDERR_FILE"
+            exit 1
+          fi
 
           developer_portal_wrapper --debug --product-name "${productName}" \
             --product-code "${productCode}" \
